language: node_js
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh; bash -ex .travis-opam.sh
node_js: "stable"
env:
  - OCAML_VERSION=4.02
script:
- eval `opam config env`
- export PATH=$PATH:/home/travis/.opam/ocaml-base-compiler.4.02.3/bin
- npm install
- npm test
